# -*- coding: utf-8 -*-
"""Untitled106.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vuYe5xUPyVyKGiHYVHMwKPdcB3Eej5lN
"""

!pip install fairlearn shap scikit-learn pandas numpy matplotlib seaborn

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score

from fairlearn.metrics import MetricFrame, selection_rate, true_positive_rate, false_positive_rate
from fairlearn.reductions import ExponentiatedGradient, DemographicParity

from sklearn.linear_model import LogisticRegression

from google.colab import files
uploaded = files.upload()

filename = list(uploaded.keys())[0]
print("Loaded:", filename)

if filename.endswith(".csv"):
    df = pd.read_csv(filename)
elif filename.endswith(".xlsx"):
    df = pd.read_excel(filename)
else:
    raise ValueError("Unsupported file type. Use CSV or Excel.")

df.head()

print("Columns in dataset:\n", df.columns.tolist())

# Copy before encoding
df_original = df.copy()

# Automatically encode categorical variables
le = LabelEncoder()
for col in df.columns:
    if df[col].dtype == "object":
        df[col] = le.fit_transform(df[col])

TARGET = 'heart_disease'
SENSITIVE = 'sex'

X = df.drop(columns=[TARGET])
y = df[TARGET]
A = df[SENSITIVE]  # sensitive attribute

X_train, X_test, y_train, y_test, A_train, A_test = train_test_split(
    X, y, A, test_size=0.2, random_state=42
)

model = LogisticRegression(max_iter=2000)
model.fit(X_train, y_train)

preds = model.predict(X_test)
acc = accuracy_score(y_test, preds)

print("Accuracy:", acc)

mf = MetricFrame(
    metrics={
        "Accuracy": accuracy_score,
        "TPR": true_positive_rate,
        "FPR": false_positive_rate,
        "Selection Rate": selection_rate
    },
    y_true=y_test,
    y_pred=preds,
    sensitive_features=A_test
)

print("Fairness by Group:")
display(mf.by_group)

mf.by_group.plot(kind="bar", figsize=(10,6))
plt.title("Fairness Metrics by Sensitive Attribute")
plt.show()

constraint = DemographicParity()

mitigator = ExponentiatedGradient(
    LogisticRegression(max_iter=2000),
    constraint
)

mitigator.fit(X_train, y_train, sensitive_features=A_train)

preds_fair = mitigator.predict(X_test)

mf_fair = MetricFrame(
    metrics={
        "Accuracy": accuracy_score,
        "TPR": true_positive_rate,
        "FPR": false_positive_rate,
        "Selection Rate": selection_rate
    },
    y_true=y_test,
    y_pred=preds_fair,
    sensitive_features=A_test
)

display(pd.concat(
    [mf.by_group.add_suffix(" (Before)"),
     mf_fair.by_group.add_suffix(" (After)")], axis=1
))

mf_fair.by_group.plot(kind="bar", figsize=(10,6))
plt.title("Fairness After Mitigation")
plt.show()

print("=== PROJECT SUMMARY ===")
print("Dataset shape:", df_original.shape)
print("Target:", TARGET)
print("Sensitive attribute:", SENSITIVE)
print("\nBaseline Accuracy:", acc)
print("\nBefore mitigation:\n", mf.by_group)
print("\nAfter mitigation:\n", mf_fair.by_group)